version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google-auth-library
    versions:
    - 6.1.6
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-map-gl
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.10
    - 6.1.11
    - 6.1.2
    - 6.1.3
    - 6.1.4
    - 6.1.5
    - 6.1.6
    - 6.1.7
    - 6.1.8
    - 6.1.9
  - dependency-name: mapbox-gl
    versions:
    - 2.0.1
    - 2.1.0
    - 2.1.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
